export enum TipoPermiso {
  PER01 = 'PER01',
  PER02 = 'PER02',
  PER03 = 'PER03',
  PER04 = 'PER04',
  PER05 = 'PER05',
  PER06 = 'PER06',
  PER07 = 'PER07',
  PER08 = 'PER08',
  PER09 = 'PER09',
  PER10 = 'PER10',
  PER11 = 'PER11',
}

export const TipoPermisoList = [
  { value: 'PER01', label: 'Permiso de refinacion' },
  { value: 'PER02', label: 'Permiso de procesamiento de gas natural' },
  { value: 'PER03', label: 'Permiso de exportacion o importacion de hidrocarburos, petroliferos o petroquimicos' },
  { value: 'PER04', label: 'Permiso de almacenamiento de hidrocarburos, petroliferos y petroquimicos' },
  { value: 'PER05', label: 'Permiso de transporte de hidrocarburos, petroliferos y petroquimicos' },
  { value: 'PER06', label: 'Permiso de distribucion de hidrocarburos, petroliferos y petroquimicos' },
  { value: 'PER07', label: 'Permiso de expendio al publico de petroliferos' },
  { value: 'PER08', label: 'Permiso de gestion de sistemas integrados' },
  { value: 'PER09', label: 'Permiso de comercializacion de hidrocarburos y petroliferos' },
  { value: 'PER10', label: 'Permiso de expendio al publico de gas natural' },
  { value: 'PER11', label: 'Permiso de distribucion por medios distintos a ducto de gas licuado de petroleo' },
];

export enum SubProductoHYP {
  SP16 = 'SP16',
  SP17 = 'SP17',
  SP18 = 'SP18',
  SP19 = 'SP19',
  SP20 = 'SP20',
  SP21 = 'SP21',
  SP22 = 'SP22',
  SP23 = 'SP23',
  SP24 = 'SP24',
  SP25 = 'SP25',
  SP26 = 'SP26',
  SP27 = 'SP27',
  SP28 = 'SP28',
  SP29 = 'SP29',
  SP30 = 'SP30',
  SP31 = 'SP31',
  SP32 = 'SP32',
  SP33 = 'SP33',
  SP34 = 'SP34',
  SP35 = 'SP35',
  SP36 = 'SP36',
  SP37 = 'SP37',
  SP38 = 'SP38',
  SP39 = 'SP39',
  SP40 = 'SP40',
  SP41 = 'SP41',
  SP42 = 'SP42',
  SP43 = 'SP43',
  SP44 = 'SP44',
  SP45 = 'SP45',
  SP46 = 'SP46',
  SP47 = 'SP47',
  SP48 = 'SP48',
}

export const SubProductoHYPList = [
  { value: 'SP16', label: 'Gasolina menor a 91 octanos' },
  { value: 'SP17', label: 'Gasolina mayor o igual a 91 y menor a 92 octanos' },
  { value: 'SP18', label: 'Gasolina mayor o igual a 92 octanos' },
  { value: 'SP19', label: 'Diesel automotriz' },
  { value: 'SP20', label: 'Diesel industrial' },
  { value: 'SP21', label: 'Diesel marino' },
  { value: 'SP22', label: 'Diesel agricola' },
  { value: 'SP23', label: 'Mezclas de gasolinas con etanol anhidro' },
  { value: 'SP24', label: 'Mezclas de diesel con biodiesel' },
  { value: 'SP25', label: 'Gas licuado de petroleo (GLP)' },
  { value: 'SP26', label: 'Gas natural para uso automotriz' },
  { value: 'SP27', label: 'Combustoleo' },
  { value: 'SP28', label: 'Turbosina (combustible para jets)' },
  { value: 'SP29', label: 'Asfaltos' },
  { value: 'SP30', label: 'Lubricantes' },
  { value: 'SP31', label: 'Parafinas' },
  { value: 'SP32', label: 'Materia prima para negro de humo' },
  { value: 'SP33', label: 'Residuo largo' },
  { value: 'SP34', label: 'Gasoleo domestico' },
  { value: 'SP35', label: 'Naftas' },
  { value: 'SP36', label: 'Propano' },
  { value: 'SP37', label: 'Butano' },
  { value: 'SP38', label: 'Etano' },
  { value: 'SP39', label: 'Metano' },
  { value: 'SP40', label: 'Pentanos' },
  { value: 'SP41', label: 'Hexano' },
  { value: 'SP42', label: 'Heptano' },
  { value: 'SP43', label: 'Kerosenos' },
  { value: 'SP44', label: 'Gasolinas de aviacion' },
  { value: 'SP45', label: 'Biodiesel puro (B100)' },
  { value: 'SP46', label: 'Etanol anhidro para mezcla' },
  { value: 'SP47', label: 'Bioturbosina' },
  { value: 'SP48', label: 'Otros petroliferos' },
];
